[2023-12-07 22:04:21,290] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data scheduled__2023-12-06T00:00:00+00:00 [queued]>
[2023-12-07 22:04:21,301] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_redshift_docker_airflow.transformar_data scheduled__2023-12-06T00:00:00+00:00 [queued]>
[2023-12-07 22:04:21,302] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:04:21,303] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-07 22:04:21,304] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-07 22:04:21,322] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-06 00:00:00+00:00
[2023-12-07 22:04:21,326] {standard_task_runner.py:52} INFO - Started process 287 to run task
[2023-12-07 22:04:21,329] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_redshift_docker_***', 'transformar_data', 'scheduled__2023-12-06T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/ETL a Redshift.py', '--cfg-path', '/tmp/tmpc7z040jl', '--error-file', '/tmp/tmpus6d9bli']
[2023-12-07 22:04:21,330] {standard_task_runner.py:80} INFO - Job 137: Subtask transformar_data
[2023-12-07 22:04:21,396] {task_command.py:371} INFO - Running <TaskInstance: ETL_redshift_docker_airflow.transformar_data scheduled__2023-12-06T00:00:00+00:00 [running]> on host 4357a10b93bd
[2023-12-07 22:04:21,486] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-07 22:04:21,533] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ManuelMoyano
AIRFLOW_CTX_DAG_ID=ETL_redshift_docker_***
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-06T00:00:00+00:00
[2023-12-07 22:04:21,537] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-06 0
[2023-12-07 22:04:21,537] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL a Redshift.py", line 122, in transformar_data
    fullpage = fullpage.sort_values('vote_average', ascending=False)
UnboundLocalError: local variable 'fullpage' referenced before assignment
[2023-12-07 22:04:21,547] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_redshift_docker_***, task_id=transformar_data, execution_date=20231206T000000, start_date=20231207T220421, end_date=20231207T220421
[2023-12-07 22:04:21,560] {standard_task_runner.py:97} ERROR - Failed to execute job 137 for task transformar_data (local variable 'fullpage' referenced before assignment; 287)
[2023-12-07 22:04:21,581] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-07 22:04:21,616] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
